# Generated by Django 4.1.7 on 2023-03-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='precio',
            new_name='precio_mesa',
        ),
        migrations.RenameField(
            model_name='silla',
            old_name='precio',
            new_name='precio_silla',
        ),
        migrations.RenameField(
            model_name='sillon',
            old_name='precio',
            new_name='precio_sillon',
        ),
    ]
