# Generated by Django 4.1.7 on 2023-03-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0002_rename_precio_mesa_precio_mesa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Silla',
            new_name='Mesas',
        ),
        migrations.RenameModel(
            old_name='Sillon',
            new_name='Sillas',
        ),
        migrations.RenameModel(
            old_name='Mesa',
            new_name='Sillones',
        ),
        migrations.RenameField(
            model_name='mesas',
            old_name='cantidad_silla',
            new_name='cantidad_mesa',
        ),
        migrations.RenameField(
            model_name='mesas',
            old_name='precio_silla',
            new_name='precio_mesa',
        ),
        migrations.RenameField(
            model_name='sillas',
            old_name='cantidad_sillon',
            new_name='cantidad_silla',
        ),
        migrations.RenameField(
            model_name='sillas',
            old_name='precio_sillon',
            new_name='precio_silla',
        ),
        migrations.RenameField(
            model_name='sillones',
            old_name='cantidad_mesa',
            new_name='cantidad_sillon',
        ),
        migrations.RenameField(
            model_name='sillones',
            old_name='precio_mesa',
            new_name='precio_sillon',
        ),
    ]
